# Standalone configuration for testing without external dependencies
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

# JWT Configuration
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 24 hours

spring:
  # Use H2 in-memory database for standalone testing
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false

  h2:
    console:
      enabled: true
      path: /h2-console

  lifecycle:
    timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:30s}

  # Disable RabbitMQ for standalone testing
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

# RabbitMQ configuration (will be ignored due to autoconfigure exclusion)
rabbitmq:
  queue:
    export:
      name: export-queue
  exchange:
    name: nexora-exchange
  routing:
    key:
      export: export.request

# Digital Ocean Spaces Configuration (using dev config values)
do:
  spaces:
    key: DO00ERAK97UGV4YAG9PW
    secret: lfuC9dusLijDr9wDKoL8UbdN8RjJ4H075AQLJyghn4k
    region: fra1
    endpoint: https://fra1.digitaloceanspaces.com
    bucket: nexora
    public-url: https://nexora.fra1.digitaloceanspaces.com

# Logging configuration
logging:
  level:
    com.nexora: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"