spring:
    datasource:
        url: ${DB_URL}
        username: ${USER_NAME}
        password: ${USER_PW}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                default_schema: ${SCHEMA}
                format_sql: false
        show-sql: false
    # Kubernetes-specific settings
    lifecycle:
        timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:30s}
# Server configuration
server:
    port: ${SERVER_PORT:8080}
    shutdown: graceful
