spring:
  application:
    name: nexora
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  graphql:
    graphiql:
      enabled: true
    path: /graphql
  jpa:
    open-in-view: false

# OpenAPI Documentation Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  packages-to-scan: com.nexora.controller
  paths-to-match: /api/**
