server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  lifecycle:
    timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:30s}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

rabbitmq:
  queue:
    export:
      name: ${RABBITMQ_QUEUE}
  exchange:
    name: ${RABBITMQ_EXCHANGE}
  routing:
    key:
      export: ${RABBITMQ_ROUTING_KEY}

cos:
  key: ${COS_KEY}
  secret: ${COS_SECRET}
  region: ${COS_REGION}
  endpoint: ${COS_ENDPOINT}
  bucket: ${COS_BUCKET}
  public-url: ${COS_PUBLIC_URL}
