spring:
    application:
        name: nexora
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}

# JWT Configuration
application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000 # 24 hours
